### ISSUE TITLE
[EPIC] Multi-channel timeseries viewer

### ISSUE THREAD

**Issue by droumis** [holoviz-topics/neuro#33]
## Summary and Links
- [`subcoordinates`](https://github.com/orgs/holoviz-topics/projects/1/views/1?filterQuery=neuro-labels%3A%22*subcoordinates*%22) (lead: ): Stacked traces on Y axis sub-coordinates
 - The intention is to avoid having to add an offset to the data values in order plot stacked on the same canvas
 - [Terminology](https://github.com/holoviz-topics/neuro/wiki/EEG-notes#terminology)

## Relevant workflows
- ephys viewer
- eeg-viewer

## Requirements

- [x] **Stacked channels**: Users should be able to vertically offset the start (left-most data point in viewport) of many timeseries at discretely spaced positions on the y-axis without having to change/copy the data.
- [x] **Hover information**: The hover tooltip should be able to display the channel name, time, and actual data value (not an offset-adjusted data value).
<details>
<summary> Hover information vid: </summary>

https://github.com/holoviz-topics/neuro/assets/6613202/23b0baa5-7b01-48b4-9e42-ca80a4a8f4ae

</details>

- [x] **Group-wise scaling of Y**: When y-wheel-zoom is active and a user's cursor is above a trace ('current trace'), all the traces in the data group to which the current trace belongs should accordingly adjust their zoom/scale when actively zoom scrolling. Notably, the extent of the data should by default not be limited to a certain y-range and instead be allowed to overlap other channels to any extent.
<details>
<summary> Group-wise scaling of Y vid (with sound): </summary>

https://github.com/holoviz-topics/neuro/assets/6613202/8e4de00f-bdbe-4b63-b3bc-3e5030b03254

</details>

- [ ] (OPTIONAL/SKIP FOR NOW)**Group-wise initial scale**: The initial scale of each data group should be settable so that it is in a reasonable range for data visibility
- [ ] (OPTIONAL/SKIP FOR NOW)**Group-wise clipping**: - above a given clipping threshold, the data should be not visible. This is sometimes used to hide large fluctuations while resolving small details without having extensive trace overlap.
<details>
<summary> Group-wise clipping vid (with sound): </summary>

https://github.com/holoviz-topics/neuro/assets/6613202/f8dcd645-1433-4a03-95d7-1746ded9258d

</details>

## Important implementation accommodations
- **[Scale bar](https://github.com/holoviz-topics/neuro/issues/34)**: The stacked traces implementation should be amenable to having a scale bar per data group
- **[minimap/rangetool](https://github.com/holoviz-topics/neuro/issues/36)**: The stacked traces implementation should be amenable to be controlled by a minimap/rangetool plot/widget
- **[Annotation](https://github.com/holoviz-topics/neuro/issues/35)**: The stacked traces implementation should be amenable to having timeseries annotations (start, end, description) as colored/labeled vertical spans across the entire viewport
- **[large data](https://github.com/holoviz-topics/neuro/issues/32)**: The stacked traces implementation should be amenable to handling large amounts data and interaction with little latency.
